micronaut:
  application:
    name: keyManagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    hello-world:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 10
    keyManager:
      address: '${KEY_MANAGER_HOST:localhost}:${KEY_MANAGER_PORT:50051}'

jackson:
  serialization:
    writeDatesAsTimestamps: false